### ISSUE TITLE
NoMethodError l_has_string? when clicking wt_update button in day view

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tkusukawa/kusu#31]
```
Hi

First big thanks for your work! It looks very cool!
But while updating some hours I have a the following problem:

When I enter some hours for a ticket in day view and click on "update" the 
following error occurs:

NoMethodError (undefined method `l_has_string?' for 
#<WorkTimeController:0xb5510da0>):
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:282:in `hour_update_check_error'
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:276:in `hour_update_check_error'
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:249:in `hour_update'
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:240:in `each'
vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:240:in 
`hour_update'
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:237:in `each'
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:237:in `hour_update'
  vendor/plugins/redmine_work_time/app/controllers/work_time_controller.rb:15:in `show'

I work with Redmine 1.0.4 and your last Version currently available.
Do you have a idea where the problem is?

Thank you for your help!
```

Original issue reported on code.google.com by `daidalo...@gmail.com` on 20 Dec 2010 at 2:43
